### ISSUE TITLE
keepdims argument to argmin() and argmax()

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#109]
The `argmin` and `argmax` functions require the `keepdims` keyword argument, same as `min` and `max`. However, in NumPy, `min` and `max` have this keyword argument, but `argmin` and `argmax` do not. We should confirm whether this keyword argument actually makes sense for these functions, or whether it was just added to these functions by mistake because they are also in the non-arg variants.

The description for `keepdims` is as follows:

> keepdims : bool
> 
> If True , the reduced axes (dimensions) must be included in the result as singleton dimensions, and, accordingly, the result must be compatible with the input array (see Broadcasting ). Otherwise, if False , the reduced axes (dimensions) must not be included in the result. Default: False .

Perhaps the reason NumPy doesn't implement this for the `arg*` functions is that they return indices, so maintaining broadcastability is not important. The documentation for [`max`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) says (emphasis added):

> If this is set to True, the axes which are reduced are left in the result as dimensions with size one. **With this option, the result will broadcast correctly against the input array.**

**Comment by kgryte** [comment]
Adding the `keepdims` keyword argument was intentional. Background can be found [here](https://github.com/data-apis/array-api/pull/23). While NumPy does not currently support `keepdims`, other libraries do (e.g., [PyTorch](https://pytorch.org/docs/stable/generated/torch.argmax.html)).

IIRC, this was discussed in a meeting and `keepdims` was affirmed to have consistency with statistical function counterparts.

**Comment by leofang** [comment]
I support to keep `keepdims`. In CuPy I raised exactly the same question before this standardization effort: https://github.com/cupy/cupy/issues/2595, and our conclusion was that it's useful and worth keeping. Quoting myself from https://github.com/cupy/cupy/issues/2595#issuecomment-559899251:
> For this case I think NumPy should change -- naively I'd expect `argmax`/`argmin`'s behavior should be the same as that of `max`/`min`, i.e. accepting a tuple `axis` and `keepdims` and so on. I wonder why they didn't do so.

**Comment by leofang** [comment]
FYI, the same issue was already raised in NumPy: https://github.com/numpy/numpy/issues/8710.

**Comment by kgryte** [comment]
@leofang Thanks for the links!

**Comment by rgommers** [comment]
Looks like we're in agreement here, so I'll close this issue. Thanks all!
