### ISSUE TITLE
Type of return value from indexing

### ISSUE THREAD

**Issue by shoyer** [data-apis/array-api#123]
The current spec is silent on what the return value from an indexing operation should be: https://data-apis.github.io/array-api/latest/API_specification/indexing.html

I propose that the return value should always be another array object, i.e., so `__getitem__` could be type annotated as `__getitem__(self: Array, key: IndexKey) -> Array`. However, this is inconsistent with NumPy, which returns NumPy scalars in some cases when indexing with integers.

**Comment by rgommers** [comment]
Thanks @shoyer. I agree with that proposal. This is what most libraries do I think - PyTorch, JAX, TensorFlow, Dask and MXNet (from memory, will verify later), with only CuPy agreeing (?) with NumPy here.

**Comment by leofang** [comment]
CuPy always returns array too.

**Comment by rgommers** [comment]
Thanks Leo. I didn't have a GPU machine at hand and couldn't find it in the docs. Turns out it's documented after all: https://docs.cupy.dev/en/stable/reference/difference.html#zero-dimensional-array

**Comment by rgommers** [comment]
This was fixed in gh-125, closing.
