### ISSUE TITLE
Should finfo have smallest normal/subnormal attributes?

### ISSUE THREAD

**Issue by rgommers** [data-apis/array-api#131]
Following up on gh-129: we removed the `tiny` attribute from `finfo` because it's badly named. In the discussion @kgryte explained its purpose and proposed instead to add two new attributes: `smallest_normal` and `smallest_subnormal`. That does sound like a good idea, however it'd be good to propose adding those attributes to `numpy.finfo` first, because it's not existing API and if NumPy doesn't want to extend `finfo` then we're better off leaving it out probably.

**Comment by rgommers** [comment]
We discussed this, and because `finfo` comes from NumPy, moved the discussion there. PR close to being merged: https://github.com/numpy/numpy/pull/18536

**Comment by rgommers** [comment]
`smallest_subnormal` seems to be painful to get right, so not sure that should be included. But `smallest_normal` makes total sense I think.

**Comment by kgryte** [comment]
This has been resolved. Closing...
