### ISSUE TITLE
Extra space after every inline code

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#139]
In the rendered spec, there is a weird formatting issue. Every piece of inline code includes an extra space after it. For example, [here](https://data-apis.github.io/array-api/latest/API_specification/array_object.html#abs-x):

<img width="378" alt="Screen Shot 2021-03-09 at 4 33 40 PM" src="https://user-images.githubusercontent.com/71486/110552829-3e918880-80f5-11eb-86f3-d5aa5802737b.png">

It looks like:

- If `x_i `is `NaN `, the result is `NaN `.

instead of

- If `x_i` is `NaN`, the result is `NaN`.

If there is already a space after the code, it is rendered as code. If there isn't, one is added. The added spaces are also there if you copy-paste the text.

I'm not sure why this is happening, if it is some issue with Myst or our theme or something else.

**Comment by rgommers** [comment]
This is an issue in https://bashtage.github.io/sphinx-material/

**Comment by asmeurer** [comment]
Looks like it is this issue https://github.com/bashtage/sphinx-material/issues/57
