### ISSUE TITLE
Top-level https://data-apis.github.io/ URLs does not work

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#141]
The top level URLs https://data-apis.github.io/ and https://data-apis.github.io/array-api/ give 404. It should be straightforward to make these work. The first can be done by adding a `data-apis.github.io` repo on this org with a simple index.html page that redirects to the main page. The other can be done similarly with an index.html on the `gh-pages` of this repo.

**Comment by rgommers** [comment]
Why would we want to do that though? The website is https://data-apis.org/ not https://data-apis.github.io/

**Comment by rgommers** [comment]
Ah that makes sense. We put up https://data-apis.github.io/array-api/latest/ as temporary for the "in progress" version, my intent was to put it at https://data-apis.org/array-api/ when the first version was final (which is going to take longer than planned earlier to arrive). But maybe we just need to do that now. Perhaps with a version switcher (latest, stable, v2021, etc.).

And/or add the link back from https://data-apis.github.io/array-api/latest/ to https://data-apis.org/. 

Either seems better than duplicate URLs.

**Comment by asmeurer** [comment]
Where is data-apis.org hosted from? Can it be moved to GitHub pages. I would have expected it to be the CNAME for the organization, which would automatically redirect all data-apis.github.io pages to the corresponding URL with data-apis.org. If that's a problem, you can use a subdomain.

**Comment by rgommers** [comment]
From the gh-pages branch of https://github.com/data-apis/data-apis.org, completely standard setup with a CNAME.

**Comment by asmeurer** [comment]
So I think we just need to rename that repo to `data-apis.github.io`. Then all other repos with gh-pages will automatically be served under that CNAME. See https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages.

**Comment by rgommers** [comment]
Renamed. https://data-apis.github.io/ works now.

**Comment by rgommers** [comment]
> The other can be done similarly with an index.html on the `gh-pages` of this repo.

Since you know what to put in that `index.html`, could you make a PR for this?

**Comment by rgommers** [comment]
Both of these links work now, I'll close this.
