### ISSUE TITLE
Device support statement refinement 

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [data-apis/array-api#157]
In the document [device support](https://data-apis.org/array-api/latest/design_topics/device_support.html#design-topics-device-support--page-root) we state

> it is important to be able to control on which device newly created arrays get placed and where execution happens.

We do mention separate needs for array allocation control and execution control.

When describing the option 3 which this data API adopts, we only talk about allocation control:

> 3. Local control via explicit keywords and a method to transfer arrays to another device.

I think it is important to explicitly add that the execution takes place local to the data, a.k.a. "computation follows data" convention. 

So I suggest we modify item 3 to say

3. Local control for data allocation target via explicit keywords, with convention that execution takes place on the same device where all argument arrays are allocated; methods for explicitly transferring data between devices.

**Comment by oleksandr-pavlyk** [comment]
Additionally, the device support document we state that method `ary.to_device(device)` must be provided, but this method is not listed in the [API specs](https://data-apis.org/array-api/latest/API_specification/index.html) document.

**Comment by rgommers** [comment]
This textual change makes sense, and we should indeed add the missing method. Thanks @oleksandr-pavlyk
