### ISSUE TITLE
Provide templates/steps for developing a toy parallel computing framework that adopts this API

### ISSUE THREAD

**Issue by learning-chip** [data-apis/array-api#163]
## The question

Hi, I just notice this project and really appreciate it. It's solving a real, important problem. I've read through all the docs but still have the following question:

Say, I want to adopt the array API standard and start building my own numpy-like framework to target some specialized/heterogenous hardware backends with my magic code optimizations -- this should be a common need for many research groups / companies. 

Before this API standard, my best reference would be JAX, CuPy, Dask, MXNet/Gluon, etc. But now the best practice must be somewhat different, as those existing, mature frameworks were developed without knowing such new API standard, and their current API design and coverage are no longer "optimal". For a brand new project, I have no backward-compatibility concerns, and no historical bagage to maintain. There must be a better, more developer-friendly way.

## Proposed documentation

Therefore, I'd like to document the recommended approaches to achieve:
- The mapping of numpy frontend to hardware devices (x86 and ARM CPU, Nvidia and AMD GPU, AI-focused ASIC, FPGA, distributed cluster). Including the proper use of DLPack and ONNX.
- The design of unit test, integration test, and compliance test. Ref: https://github.com/data-apis/array-api-tests
- Reuse code in scipy/sklearn, once their internal C/Fortran dependencies are cleaned-up. Relevant project: unumpy https://github.com/Quansight-Labs/unumpy
- Reuse the autodiff implementation in autograd/JAX/MXNet/etc, if that's a reasonable goal.
- Reuse the graph-level performance optimization in TVM / MLIR / XLA HLO, if that's not out-of-score.
- Maybe even reuse the Profiler Dashboard in Dask, as well as other add-on tools in the numpy ecosystem.

Those documented approaches might not be "the best solution", as there are a thousand ways to target heterogenous hardware and optimize performance. I by no means want to mix "standard" and "implementation". Just need a viable, proven way for new developers to get started.

## Proposed tutorial/template

Besides providing documentation and advice, a more practical thing is -- a minimum toy example that adopts this API standard and runs under a multi-threaded CPU or a single GPU card. The API coverage doesn't need to be complete. Even just implementing 5~10 numpy funcs (add, matmul, sin, exp, ...) would be a very useful reference. It will show up as a beginner-level, end-to-end tutorial like [Dive into Deep Learning Compiler](https://tvm.d2l.ai/) or [My First Language Frontend with LLVM](https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/index.html). I am happy to contribute one, but would need some advice on where to start.

**Comment by rgommers** [comment]
Hey @learning-chip, thanks for the ideas. There's quite a bit to unpack here - let me try.

> Therefore, I'd like to document the recommended approaches to achieve:

A main point of this API standard is to decouple API syntax and semantics from particular implementations. So the "how do I implement this" question is mostly out of scope for this standard (and this particular repo) on purpose. That said, if we can make it easier to create new implementations, it would make perfect sense to do that.

> * The mapping of numpy frontend to hardware devices (x86 and ARM CPU, Nvidia and AMD GPU, AI-focused ASIC, FPGA, distributed cluster). Including the proper use of DLPack and ONNX.

For DLPack there's a list of implementations at https://github.com/data-apis/consortium-feedback/issues/1#issuecomment-726066249. For ONNX I'm not sure, it's complementary to but different from this standard. Maybe @szha has a pointer here.

For particular hardware, I don't think there's one best way of doing something. There's not much to say here, except for pointing at current libraries.

> The design of unit test, integration test, and compliance test. Ref: https://github.com/data-apis/array-api-tests

Yes, this we do provide indeed. This should be a huge help when writing a new implementation. We also plan to create a portable benchmark suite in the future. 

> Reuse code in scipy/sklearn, once their internal C/Fortran dependencies are cleaned-up. Relevant project: unumpy https://github.com/Quansight-Labs/unumpy

There's efforts underway to do more for SciPy, and various libraries (JAX, CuPy, PyTorch, RAPIDS) are also implementing scipy-compatible submodules.

> Reuse the autodiff implementation in autograd/JAX/MXNet/etc, if that's a reasonable goal.

I'm not sure. `autograd` is no longer maintained. There was an announcement on the numpy mailing list recently about a new `autograd`-inspired project.

> Reuse the graph-level performance optimization in TVM / MLIR / XLA HLO, if that's not out-of-score.

Certainly out of scope for this project, and I personally don't know the trade-offs/use-cases for choosing between them.

> Maybe even reuse the Profiler Dashboard in Dask, as well as other add-on tools in the numpy ecosystem.

Again, probably not a bad idea, but pretty far out of scope for this standard.

> I by no means want to mix "standard" and "implementation". Just need a viable, proven way for new developers to get started.

I do think that writing a whole new library from scratch is still a large undertaking, especially when you want to add in things like autograd and graph optimizations.  Even just a plain numpy-like library (CPU-only, no autograd) has proven a big challenge in other language ecosystems. So I'm not sure there's a simple "viable way to get started".

> Besides providing documentation and advice, a more practical thing is -- a minimum toy example that adopts this API standard and runs under a multi-threaded CPU or a single GPU card. The API coverage doesn't need to be complete. Even just implementing 5~10 numpy funcs (add, matmul, sin, exp, ...) would be a very useful reference.

If you really want a parallel numpy, here's an example: https://github.com/quansight/pnumpy. Of course that's still tied to NumPy. If you'd want to start from scratch with a clean slate and good design principles, the first thing to do is not mix C/C++ with use of the CPython API. So best not to base it on NumPy.

Other than that, there's a lot of ways you can go. For a parallel and performant numpy-like thing, you may want to start from https://github.com/xtensor-stack/xtensor and combine it with this array API standard. That's about as low-effort as it gets, and would actually be a really valuable contribution.

**Comment by learning-chip** [comment]
Thanks! Those are all very useful replies. Closing the issue for now.

> If you'd want to start from scratch with a clean slate and good design principles, the first thing to do is not mix C/C++ with use of the CPython API. So best not to base it on NumPy.

That's a particularly good point...
