### ISSUE TITLE
Making indexing more strict?

### ISSUE THREAD

**Issue by seberg** [data-apis/array-api#188]
*As per my comment [here](https://github.com/numpy/numpy/pull/18585#discussion_r644998943)*

> Beyond "why not", I wonder if there is even a point in allowing arr[boolean_index,] as opposed to just arr[boolean_index].
>
> I admit, since it does not preclude arr_nd[boolean_index_1d, ...] it probably doesn't matter. On the other hand, it seems unnecessary to force arra-likes to implement it. It seems fine for an object to define arr_nd[boolean_index_1d, ...], but regard arr_nd[boolean_index_nd,] as malformed (because it indexes dimension 1 with an N-D index, rather than a 1-D one).

*And [here](https://github.com/numpy/numpy/pull/18585#discussion_r644982946) about SymPy's way of indexing a Matrix*

I don't really agree that SymPy matrices are super weird.  I quite like the way they think about elements rather than dimensional indexing.  And I think especially with respect to `__len__` and `__iter__` it would make sense to only strictly define `arr_1d[integer]` and but not `arr_2d[integer]`.  The latter can be spelled explicitly using `arr_2d[integer, ...]` or `arr_2d[integer, :]` which is *much* more clear and unambiguous. (even `arr_2d[integer,]` is fine in theory.)

The "downside" is that you don't try to copy the python lists-of-lists analogy.  But I am not sure its a particularly good one in any case?

**Comment by rgommers** [comment]
Missing a bit of context/knowledge on SymPy here, so can't comment on everything - but definitely agree with not allowing `arr_2d[integer]`!

> The "downside" is that you don't try to copy the python lists-of-lists analogy. But I am not sure its a particularly good one in any case?

Agree, not much of a downside.

**Comment by seberg** [comment]
Just for reference on SymPy:
```python
In [3]: m = sympy.Matrix([[1, 2], [3, 4]])

In [4]: m[0]
Out[4]: 1

In [5]: list(m)  # via __iter__
Out[5]: [1, 2, 3, 4]
```
SymPy does flat indexing for a single integer index, since it does flat iteration.

**Comment by rgommers** [comment]
> (even `arr_2d[integer,]` is fine in theory.)

I think what we'd like is to make indexing unambiguous. Which means (to me at least) to specify an index for all axes with some valid method (integer, slice, ellipsis). Both `arr_2d[integer]` and `arr_2d[integer,]` fail to do that, so I think if we forbid one we should forbid both of those forms.

> SymPy does flat indexing for a single integer index, since it does flat iteration.

I guess we'd want that spelled `reshape(x, (-1,))[integer]`
