### ISSUE TITLE
Make it clear that the DLPack protocol is *not* part of the array API standard

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api#192]
See the discussion around https://github.com/numpy/numpy/pull/19083#issuecomment-854926910. We should make it clear that any library is free to implement `__dlpack__` and `__dlpack_device__`, and `from_dlpack()` can return a non-array-API-complaint object. 

Ideally, the second half of this page https://data-apis.org/array-api/latest/design_topics/data_interchange.html should not live in the array API standard, but instead in DLPack's website so that we can simply link to it. Unfortunately DLPack doesn't seem to plan on creating a website in the near future, so perhaps we can add a big warning mark during the rewriting planned in https://github.com/data-apis/array-api/pull/185?

**Comment by rgommers** [comment]
Thanks @leofang, good points. My plan was to contribute docs to DLPack, maybe as a new Sphinx site.
