### ISSUE TITLE
Specify whether `bitwise_right-shift` uses arithmetic or logical shifts

### ISSUE THREAD

**Issue by rgommers** [data-apis/array-api#195]
From https://github.com/pytorch/pytorch/pull/59544#discussion_r648003584:

_For a left shift it doesn't matter whether these are logical or arithmetic shifts (https://en.wikipedia.org/wiki/Arithmetic_shift#Equivalence_of_arithmetic_and_logical_left_shifts_and_multiplication), but for a right shift it does matter._

_Is this a logical or an arithmetic shift?_

The `<<`, `>>` operators, numpy and pytorch are all consistent with each it looks like:
```
>>> 10 << 1
20
>>> 10 >> 1
5
>>> -10 >> 1
-5
>>> -11 >> 1
-6

>>> t = torch.Tensor([10])
>>> t
tensor([10.])
>>> t << 1
tensor([20.])
>>> t >> 1
tensor([5.])
>>> t = torch.Tensor([-10])
>>> t << 1
tensor([-20.])
>>> t >> 1
tensor([-5.])

>>> def f(x, shift=1):
...     x2 = np.right_shift(x, shift)
...     print(f'Original ({x}):  {np.binary_repr(x)}')
...     print(f'Shifted ({x2}): {np.binary_repr(x2)}')
... 
... 
>>> f(10)
Original (10):  1010
Shifted (5): 101
>>> f(-10)
Original (-10):  -1010
Shifted (-5): -101
```
IIRC this is arithmetic shifting for negative integers.

@kgryte could you verify and add a description to the `bitwise_right_shift` documentation?

**Comment by kgryte** [comment]
Verified. This should be specified as an arithmetic shift, thus matching Python semantics. I've opened #200 to add a note to the specification.
