### ISSUE TITLE
[Consistency] `Raises` section within linalg

### ISSUE THREAD

**Issue by Lezcano** [data-apis/array-api#208]
Currently, the only function that specifies a `Raises` section in [Extensions / Linear Algebra Functions](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html) is [`matrix_power`](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html#raises).

I would assume that we would want to either specify this for all the functions (which would be quite tricky, as it would involve defining when is a spectrum non-singular or when is a matrix SPD), or for none of them.

cc @rgommers @mruberry

**Comment by asmeurer** [comment]
I don't know if this is clearly spelled out, but generally when exceptions are not explicitly required by the spec, it means libraries are allowed to raise an exception or to do something else, which may vary depending on how the libraries work. Even so, I don't know if the current spec gives proper allowances for libraries potentially raising exceptions for things like that if they want to.

**Comment by rgommers** [comment]
`Raises` can simply be removed here I think. The two conditions are:

1. if the innermost two dimensions of x are not the same size (i.e., form square matrices).
2. if n is less than zero and a square matrix is not invertible.

Those are also captured by the conditions given in the parameter descriptions, so `Raises` adds nothing of interest.
