### ISSUE TITLE
[Consistency] Definition of the properties of the output

### ISSUE THREAD

**Issue by Lezcano** [data-apis/array-api#209]
Some functions such as [`linalg.qr`](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html?highlight=ndim#linalg-qr-x-mode-reduced) define the properties that the outputs should have---`Q` orthogonal, `R` upper-triangular---but others such as [`linalg.eigh`](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html?linalg-eigh-x-upper-false#linalg-eigh-x-upper-false) do not.

I believe that it would be best to specify the properties that these matrices should have in the definition of each function.

cc @rgommers @mruberry

**Comment by rgommers** [comment]
Makes sense to me to improve the descriptions here, thanks @Lezcano .
