### ISSUE TITLE
[Errata] Third return argument in SVD goes by a non-standard name

### ISSUE THREAD

**Issue by Lezcano** [data-apis/array-api#210]
The third return of [`linalg.svd`](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html#linalg-svd-x-full-matrices-true) goes by the name of `v`, but it is of shape `(k, n)` where `k=min(m,n)`. This is not standard, as a (real) SVD decomposition is something of the form `A = USV^T`, where the columns of `U` and `V` hold the left and right singular values respectively.

In [PyTorch](https://pytorch.org/docs/stable/generated/torch.linalg.svd.html), we solve this by calling this argument `vh` to account for the fact that the complex SVD takes the form `A = USV^H`. The same convention is followed in [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html).

To avoid these problems, it would be good to specify the actual definitions of the decomposition, even if this is not done in a completely formal way. This is proposed in https://github.com/data-apis/array-api/issues/209

cc @rgommers @mruberry

**Comment by asmeurer** [comment]
It should be pointed out that this is more than just a question of wording in the spec. The names of the namedtuple parameters are part of the API, so they need to be uniform across compliant libraries.

**Comment by rgommers** [comment]
Naming the argument `vh` sounds good to me.

**Comment by kgryte** [comment]
The use of `v` was a hold over from the original proposal, which, if I recall correctly, followed TF. This was subsequently [amended](https://github.com/data-apis/array-api/pull/114/commits/1ffd531b3d94a4cfc254e84e8179f9bc1e3ebdbb) in order to follow NumPy, et al.

Accordingly, renaming as `vh` is fine with me.
