### ISSUE TITLE
Proposal: use entrypoints to make array-api submodules discoverable

### ISSUE THREAD

**Issue by Zac-HD** [data-apis/array-api#244]
Over in https://github.com/HypothesisWorks/hypothesis/pull/3065, we're working on test tooling that takes an array-api implementation (e.g. `numpy.array_api`, etc) and returns test helpers which use that implementation.  For ergonomics we'd also like to automatically find the array-api implementation, if there is one, for a given module - but as I understand it there's no way to discover that mapping.  Yet!

I therefore propose that as part of the Array API standard, packages implementing the API should register an entry point declaring which (sub)module contains the implementation.  For example, Numpy would [register](https://github.com/numpy/numpy/blob/90ddaa5f88cab3b9143877aa1bb78f80fc38a9ac/setup.py#L411-L413):

```python
        entry_points={
            'console_scripts': f2py_cmds,
            'array_api': ['numpy = numpy.array_api'],  # new: maps top-level name to array api implementation
        },
```

Implementations can then be found using `importlib.metadata` ([see here for < py3.7](https://github.com/HypothesisWorks/hypothesis/blob/bf2c4be6f86ccb88a496373b24e92ad8e270bc01/hypothesis-python/src/hypothesis/entry_points.py)) as follows:

```python
import numpy.array_api
from importlib.metadata import entry_points

try:
    eps = entry_points(group="array_api")
except TypeError:
    # Load-time selection requires Python >= 3.10 or importlib_metadata >= 3.6, so fallback:
    eps = importlib_metadata.entry_points().get("array_api", [])
implementations = {entry.name: entry for entry in eps}

npa = implementations["numpy"].load()
assert npa is numpy.array_api
```

This allows us to avoid hard-coded lists of known libraries and locations, which will inevitably be both incomplete and out of date as the ecosystem evolves.  It also makes it easy to find all installed array-api implementations, supporting a much wider range of purposes than testing 🎉

**Comment by rgommers** [comment]
Thanks @Zac-HD! Discoverability sounds like a great idea. 

`importlib` is part of the stdlib, so that sounds fine. For registering an entry-point, my memory is a bit fuzzy about whether it can be done without `setuptools`. That seems desirable, since it's not a pleasant dependency to require every library to have, and we'll likely move NumPy away from it before `distutils` disappears from the stdlib.

**Comment by Zac-HD** [comment]
https://packaging.python.org/specifications/entry-points/ says:

> The entry point file format was originally developed to allow packages built with `setuptools` to provide integration point metadata that would be read at runtime with `importlib.metadata`. It is now defined as a PyPA interoperability specification in order to allow build tools other than `setuptools` to publish `importlib.metadata` compatible entry point metadata, and runtime libraries other than `importlib.metadata` to portably read published entry point metadata (potentially with different caching and conflict resolution strategies).

So I think we're set there, though I can't speak to how well other tools support the standard or how to use them.

**Comment by Zac-HD** [comment]
CC also @asmeurer - programatic discovery of implementations seems useful for the test suite 😉

**Comment by rgommers** [comment]
Cool, thanks. If there are other tools that can do it but need some fixes, or even if we can write a tiny package that does exactly this job and nothing else, then that's fine imho.

**Comment by kgryte** [comment]
@honno I think a reasonable inclusion place would be in the "How to adopt this API" [section](https://github.com/data-apis/array-api/blob/5ecbce416aa46d642b98d9568625250fec323fc4/spec/purpose_and_scope.md#how-to-adopt-this-api) of the specification. Feel free to submit a PR adding this guidance. :)
