### ISSUE TITLE
Interplay between `copy` and `device` in `asarray()`?

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api#254]
I feel we might need some clarification, but maybe we can start with a quick discussion.

I could be wrong, but we probably missed this in #96: What happens when we call `asarray` on an array on device 0 but set `copy=False` and `device=device 1`? Do we raise `ValueError` (as in other `copy=False` cases where a copy must be done), or do we ignore `copy` as the user clearly knows in this case a copy among the two devices is inevitable?

Another question: We probably owe it to clarify this in `asarray()` too, as in other `*_like()` cases?
``` 
If `device` is `None`, the default device must be used, not `x.device`.
```

**Comment by leofang** [comment]
> I'd suggest just raising the exception, because the two keywords provided conflict.

Thanks, Ralf! Sounds good to me. I forgot we had [this section](https://data-apis.org/array-api/latest/design_topics/device_support.html#semantics) that also provides the same answer to my question.

> Although we may want to change that default in `*_like`. 

Why? I thought the default is fine.

> But either way `asarray` should say what its behavior is.

I'll send a PR to address this.

**Comment by rgommers** [comment]
> Why? I thought the default is fine.

If you use `_like` then it's typically for doing operations within some function, e.g.:
```python
def func(x):
    y = ones_like(x)
    z = some_other_func(x, y)
    return z
```
If by default `x` and y` are not guaranteed to be on the same device, that's a bit of a foot gun. For other creation functions there's no array input, so the default device for the library is reasonable. But if there's an input array, it has a `.device` attribute, so that seems like a better default.

**Comment by leofang** [comment]
@rgommers I am glad you are undergoing the same thinking process as I did 😆 Let me direct you to your previous https://github.com/data-apis/array-api/pull/96#discussion_r546407042.
