### ISSUE TITLE
Proposal: Remove: `xp.positive()`

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api#255]
There's a [`positive()`](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#positive-x) function but also an [`abs()`](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#abs-x) function. They look the same to me, or largely are. Can we remove `positive()`? I personally never see it used in either user code or library code.

**Comment by rgommers** [comment]
The reason it was added is that we have a design that there should be a matching set of public function for each Python operator and dunder method. There was at least one concrete use case where a library, I believe it was Vaex, needed functions. If only one function is missing the gap can be plugged, with `operator.pos` in this case, but the preference was to just aim for 100% completeness. So I'd prefer to keep it, even though I agree it'll be rare to see `positive` used.

**Comment by asmeurer** [comment]
`positive` is not the same as `abs`. It's a no-op (the same as `+x`). Unless a library uses + as some way to reify an array, it does nothing (I don't know if any array libraries do anything with `+x`, but e.g., the standard library [decimal](https://docs.python.org/3/library/decimal.html) uses `+x` to reapply the global precision).

**Comment by leofang** [comment]
Thanks for quick replies @rgommers @asmeurer!
> The reason it was added is that we have a design that there should be a matching set of public function for each Python operator and dunder method.

> positive is not the same as abs. It's a no-op (the same as +x).

I overlooked these points. Thanks for clarifying. I believe we can close this issue 🙂
