### ISSUE TITLE
Clarify whether single-axis indices can be tuples i.e. `x[(i,)]`

### ISSUE THREAD

**Issue by honno** [data-apis/array-api#257]
Currently `numpy.array_api` supports this behaviour. For example:

```
>>> x = xp.zeros(5)
>>> x[(0,)]
Array(0)
```

Also notably @asmeurer tests for `(i,)` indices in the compliance suite's multiaxis tests.

I can't work out whether the indexing rules specify this is allowed or not (i.e. not explicitly mentioned in either the single or multi-axis sections), but I would imagine this is expected. Before this was mentioned by @Zac-HD in HypothesisWorks/hypothesis#3065, I had just assumed that multi meant "one-or-more" and so this is allowed.

Let me know if I'm wrong and you can guarantee this with the current spec, although that raises the question if we could still purposely note this.

Clarification either way would be nice, but if this isn't actually agreed upon then I'd just add that allowing `(i,)` indices would make index tooling (like in Hypothesis) much simpler.

**Comment by asmeurer** [comment]
I understand that as a multi-axis index that selects 1 axis. Maybe the multi-axis indexing section could say something like "a multi-axis index indexes between 0 and N indices (inclusive)".

**Comment by kgryte** [comment]
The following note in the spec implies that single-element tuples are the equivalent of single-axis indices:

> In Python, `x[(exp1, exp2, ..., expN)]` is equivalent to `x[exp1, exp2, ..., expN]`; the latter is syntactic sugar for the former.

However, I've submitted [gh-280](https://github.com/data-apis/array-api/pull/280) to provide some additional guidance.
