### ISSUE TITLE
Cross-kind casting in asarray()

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#264]
Should asarray() allow arbitrary casting between dtypes if you call `asarray(x, dtype=dtype)`? It isn't really clear in the spec if, e.g., `asarray(x, dtype=bool)` should be required to work if x is an integer or float array, or `asarray(x, dtype=float64)` if x is integer, and so on. My feeling is that it definitely should work if `dtype` is a promotable type from `x.dtype`, but I don't know if casts that aren't required to promote should also be required to work.

**Comment by rgommers** [comment]
I'd expect this to work, because it's explicit. Unless there's an obvious alternative, like `x.astype()` (which we don't have).

**Comment by asmeurer** [comment]
This is also relevant for the `*_like` creation functions, which all accept a `dtype` parameter. https://data-apis.org/array-api/latest/API_specification/creation_functions.html

**Comment by asmeurer** [comment]
I guess there's actually three levels of dtype casting:

- Promotable casting (`x.dtype` can be promoted to `dtype` in the [type promotion table](https://data-apis.org/array-api/latest/API_specification/type_promotion.html)
- Same-kind casting (`x.dtype` is the same kind as `dtype` but may be a downcast, like int64 -> int8 or uint64 -> int64)
- Cross-kind casting (`x.dtype` and `dtype` are different kinds (integer, floating-point, boolean, eventually complex)).

Presumably at the very least promotion should be allowed, otherwise the dtype parameter is useless, especially for the `*_like` functions. The other two involve losing information for some values (except for bool -> other).

**Comment by kgryte** [comment]
@asmeurer I am not seeing how the `*_like` functions are affected by cross-kind casting, as discussed in this issue. Maybe I am missing something, but the `*_like` functions don't perform casting; the data of the input array is not touched.

**Comment by asmeurer** [comment]
Oh yeah you are right about the _like functions (those always confuse me tbh because they seem rather pointless, but that's neither here nor there).
