### ISSUE TITLE
Explicit rules about zero-dimensional tensors

### ISSUE THREAD

**Issue by arogozhnikov** [data-apis/array-api#279]
Documentation mentions in several places zero-dimensional tensors, but it's not clear to me if those are required to be supported.

While it sounds very reasonable to assume that e.g. xp.sum(x) returns scalar, some of frameworks don't provide support for zero-dimensional arrays, and fake it with 1-element 1-dimensional arrays. Examples:
- mxnet fails on creation `mx.nd.zeros([])` I know API will be reworked in mxnet 2, but did not check actual support there
- paddle also lacks zero-dim arrays, it does not seem to be in any priority

**Comment by rgommers** [comment]
Thanks for pointing that out @arogozhnikov! 0-D arrays are required, so we should make that more explicit.

**Comment by rgommers** [comment]
I'm not sure we need a whole separate section, just a note near the top of https://data-apis.org/array-api/latest/API_specification/array_object.html should be fine I think?

**Comment by kgryte** [comment]
Okay. Will add.
