### ISSUE TITLE
Add `unique_counts()`?

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api#291]
This is a follow-up of #275. I've found `numpy.unique(x, return_counts=True)` quite useful. It allows us to build a histogram for the input array `x`. I'd suggest us to add the following function:
```python
def unique_counts(x, /):
   """
   return a tuple of two arrays (unique values and counts)
   """
```

**Comment by leofang** [comment]
Can we target this for v2021?

**Comment by leofang** [comment]
I'll work on this as per the discussion in today's call.

**Comment by kgryte** [comment]
Thanks @leofang!

**Comment by rgommers** [comment]
Seems very reasonable, and if we add it we should indeed add it to the `v2021` milestone. Better to do all four new `unique_*` functions in one go.
