### ISSUE TITLE
axis argument to matrix_norm

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#318]
The matrix_norm function has an axis argument to specify the axes that the matrices are stacked on, defaulting to the last two axes. This is currently the only matrix function that allows specifying this. All other matrix functions assume matrices are stacked on the last two axes. To work with stacks on other axes, the array axes must first be transposed using something like `permute_dims`.

The axis/axes argument is present in vector_norm, cross, and tensordot, but the first two of those operate on 1-D vectors and the last operates on arbitrary tensors. The axis argument to matrix_norm is a holdover from the split of `norm`, which handled both matrix and vector norms at the same time.

**Comment by kgryte** [comment]
@Lezcano You have thoughts on this?

**Comment by kgryte** [comment]
This may be an instance where we want to remove the `axis` argument from the spec and consider its addition in the 2022 revision of the standard. This would not disbar PyTorch from continuing to support a `dim` kwarg, but would allow more time for array conforming libraries to access whether they would also prefer to support the ability to specify axes.

**Comment by Lezcano** [comment]
I think @kgryte 's comment is on point. Removing things from the API and revisit these points in a later revision of the API is always easier.

**Comment by kgryte** [comment]
Okay. Will submit a PR removing support for the `axis` argument. Thanks, @Lezcano, @leofang, and @asmeurer!
