### ISSUE TITLE
Specify behaviour for `std()` and `var()` when `N == 1`

### ISSUE THREAD

**Issue by honno** [data-apis/array-api#334]
Currently [`std()`](https://data-apis.org/array-api/latest/API_specification/statistical_functions.html#std-x-axis-none-correction-0-0-keepdims-false) and [`var()`](https://data-apis.org/array-api/latest/API_specification/statistical_functions.html#var-x-axis-none-correction-0-0-keepdims-false) don't specify behaviour when `N` (number of elements to compute with, i.e. `x.size` if `axis=None`) is 1.

```python
>>> np.std(np.asarray(42.))
0.0
>>> torch.std(torch.as_tensor(42.))
tensor(nan)
```

If specific behaviour here isn't necessary for anything, this seems like an easy thing to note as unspecified.

**Comment by kgryte** [comment]
@honno This is (somewhat) specified. See [here](https://github.com/data-apis/array-api/blob/main/spec/API_specification/statistical_functions.md#special-cases-2).

> if `N - correction` is less than or equal to `0`, the standard deviation is `NaN`.

When `N - correction` equals unity, the result should be `0`. This follows from, when you have only a single element, there is no variance based on the definition variance, as the mean is equal to the element (i.e., `1/n sum_1^1 (x_i - mu)^2`).

Torch is simply wrong here.

**Comment by honno** [comment]
With say a 0d array e.g. `x = xp.asarray(42.)`, isn't `N == 1` given the `std()`/`var()` default of `axis=None`? Given `correction=0.0`, the special case `N - correction == 1` won't apply.

**Comment by kgryte** [comment]
Yes, `N==1`. The spec doesn't include `N - correction = 1` as a special case, as this should not be controversial given the definition of the variance. The result should be `0` when `N - correction = 1`. Just like the mean should be equal to `x_i` when all `x_i` equal the same value, but we don't list that as a special case as it arises naturally from the definition of the arithmetic mean. So, too, does `var` and `std` equal to `0` based on the definitions of the variance and standard deviation.

**Comment by kgryte** [comment]
As `N==1` is not a "special case", the result should always be `0`, and IMO we should not need to explicitly spell this out as a special case in the spec, will close this out.
