### ISSUE TITLE
linalg.vecdot and vecdot have (midly) diverging defaults.

### ISSUE THREAD

**Issue by Lezcano** [data-apis/array-api#355]
Their signatures are:
`linalg.vecdot(x1, x2, /, *, axis=None)`

`vecdot(x1, x2, /, *, axis=-1)`

I'd certainly prefer to settle for `axis=-1`.

**Comment by rgommers** [comment]
Ouch, that seems like a bug to me, good catch @Lezcano.

**Comment by asmeurer** [comment]
I think this was just an oversight https://github.com/data-apis/array-api/pull/281

**Comment by kgryte** [comment]
This has been addressed in https://github.com/data-apis/array-api/pull/358.
