### ISSUE TITLE
Allowing `None` for indexing to add an axis

### ISSUE THREAD

**Issue by jakirkham** [data-apis/array-api#360]
In many array libraries today, one can use `None` when indexing to add a singleton dimension like `np.newaxis`. Would be good to support in the standard as well.

**Comment by rgommers** [comment]
Thanks @jakirkham. I think this one fell through the cracks so far. `x[:, None, :]` is equivalent to `expand_dims(x, axis=1)`, the latter is in the standard so at least there's an easy alternative.

I just tested and it looks like every library supports indexing with `None` with consistent behavior. So we should just add this I think.

**Comment by asmeurer** [comment]
We should probably also add `newaxis = None` to the namespace.

**Comment by kgryte** [comment]
I've opened https://github.com/data-apis/array-api/pull/408 which adds support for expanding dimensions via `None`.
