### ISSUE TITLE
Divide functions have ambiguous specification for integer inputs

### ISSUE THREAD

**Issue by honno** [data-apis/array-api#361]
[`divide()`](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#divide-x1-x2) (and `__truediv__`/`__itruediv__`) allows `x1` and `x2` to be integer arrays, but the ouput is specified as a floating array determined by type promotion, which int types can't promote to.

The spec should either clarify behaviour for both mixed int/float array and two int array scenarios, or note they are out-of-scope similiar to [`pow()`](https://data-apis.org/array-api/latest/API_specification/array_object.html#pow-self-other).

**Comment by kgryte** [comment]
The spec can be updated with a note similar to `pow`. Feel free to submit a PR with the proposed changes.
