### ISSUE TITLE
Could mean accept an optional weights parameter?

### ISSUE THREAD

**Issue by NeilGirdhar** [data-apis/array-api#366]
This would allow `mean` to subsume `average` (https://numpy.org/doc/stable/reference/generated/numpy.average.html).

**Comment by kgryte** [comment]
Hey @NeilGirdhar, thanks for raising this question.

I have a couple of concerns regarding adding support for computing a weighted mean.

1.  Computing a weighted mean does not appear to be widely supported across array [libraries](https://github.com/data-apis/array-api-comparison/blob/a2fdc6b7a7ac4728519785550c6cf25a7ca69973/data/join.csv#L45).
2.  If we extended the behavior of `mean`, this would beg the question as to whether other statistical functions should also support weights (e.g., `var`, `std`, `sum`, `prod`, etc). I am not sure there is appetite for such extensions across array libraries.
3.  While the arithmetic mean is a special case of the weighted mean and supporting weights would allow generalization, my sense is that, similar to NumPy, computing the weighted mean may be better reserved for a separate dedicated API (e.g., `wmean`). However, given that such an API does not enjoy broad support, I am not overly optimistic that this would garner the necessary momentum to be added to the specification at this time.

This proposal could always be revisited in the future should we observe greater support for such an API across array libraries.

Others may have a different opinion.

**Comment by rgommers** [comment]
"what do weights mean" is also a never-ending source of discussions. There's multiple reasonable ways of specifying them, and in SciPy we haven't gotten to a consistent story across modules yet after quite a few years of revisiting the topic every so often. So I tend to agree that we probably want to steer clear of adding weights to existing functions.

**Comment by NeilGirdhar** [comment]
Okay, that makes sense.  Thanks for considering it.
