### ISSUE TITLE
Versioning in the spec URLs

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#398]
https://github.com/data-apis/array-api/pull/394 gives a way we can add a version menu to select different versions of the spec once we release things. 

We should decide how we are going to name the versions in the URLs, so that we don't end up changing things and breaking the URLs. For example https://data-apis.org/array-api/latest/index.html

My suggestions:

- Right now where the URLs say `latest` we should write the full version number (e.g., https://data-apis.org/array-api/2022.02/index.html)
- We should continue to have `latest`, which always redirects to the latest version of the spec. I'm not sure if it should be a literal redirect or just a copy. If we did a redirect, any URL would always redirect to something that will be stable and always point to that exact version. With no redirect, a "latest" page will give a URL that will change whenever we do a release. The effective difference is the behavior when someone copies the URL from their browser.
- We need something that can point to the development version of the spec. I would suggest using something like `draft` or `development`. 

The main index page should always point to `latest`. We might also consider adding headers to the development version that warn people that it isn't a released version.

**Comment by kgryte** [comment]
This should now be addressed. Namely,

- `latest` redirects to the latest specification revision.
- `draft` serves as the development version.
- the main `index.html` page redirects, similar to `latest`, to the latest specification revision.
