### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [data-apis/array-api#423]
The previous valid URL

https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.stack.html#signatures.manipulation_functions.stack

is now broken. It does not redirect to intended

https://data-apis.org/array-api/2021.12/API_specification/generated/signatures.manipulation_functions.stack.html#signatures.manipulation_functions.stack

At the same time https://data-apis.org/array-api/latest does redirect to https://data-apis.org/array-api/2021.12 

Most of previously recorded (bookmarked, used in mark-down or RST documents) references are now broken.

**Comment by kgryte** [comment]
@oleksandr-pavlyk Thanks for reporting. This should now be resolved. The above links now resolve correctly.
