### ISSUE TITLE
Regarding return type of matrix_rank in Linear_Algebra module

### ISSUE THREAD

**Issue by RickSanchezStoic** [data-apis/array-api#469]
https://data-apis.org/array-api/latest/extensions/generated/signatures.linalg.matrix_rank.html states that the return type should be `float`. Is this correct? If so, why is that? All the frameworks : `torch`, `TensorFlow` , `Jax` return an `int` type or variant.

**Comment by kgryte** [comment]
@RickSanchezStoic Thanks for filing this issue. You are correct. The return type should be the default integer data type.
