### ISSUE TITLE
Rationale behind not setting positional arguments to positional only for few functions.

### ISSUE THREAD

**Issue by RickSanchezStoic** [data-apis/array-api#475]
Functions like `full` and `ones` and maybe others don't have positional only arguments in their definition. I wanted to know the reason behind this. https://data-apis.org/array-api/latest/API_specification/creation_functions.html?highlight=positional

**Comment by kgryte** [comment]
This was changed in https://github.com/data-apis/array-api/pull/167 and stemmed from the following issue: https://github.com/data-apis/array-api/issues/85.

**Comment by RickSanchezStoic** [comment]
Thanks, @kgryte! Do you think there should be some detail about this in the official documentation to avoid confusion in the future?

**Comment by kgryte** [comment]
Agreed. We have an open issue to consolidate some of the spec guidance (see https://github.com/data-apis/array-api/issues/223), and, as part of addressing the concerns described there, can add an explainer regarding exceptions to the general rule.
