### ISSUE TITLE
Add `clip`

### ISSUE THREAD

**Issue by jakirkham** [data-apis/array-api#482]
The `clip` function is quite handy for constraining data to a certain range. Would be nice to include this in the spec

**Comment by rgommers** [comment]
gh-187 says `clip` is universally implemented by libraries. This looks to me like a useful function to add. IIRC we had some issues with `clip` behavior in `numpy`, we should dig those up to check for possible semantics issues.

**Comment by rgommers** [comment]
> IIRC we had some issues with `clip` behavior in `numpy`, we should dig those up to check for possible semantics issues.

This wasn't too bad actually, a lot of it was segfaults and whether it was a ufunc or not. The relevant ones:
- Semantics when the max value is smaller than the min value: https://github.com/numpy/numpy/issues/18782. Probably not very interesting, just undefined behavior,
- Whether or not the output dtype should depend on the dtype of the min/max values: https://github.com/numpy/numpy/issues/16609. Not immediately clear to me what the right answer is here.

And of course we need to choose keyword names, always a hard problem. Existing signatures don't match:
- `np.clip(a, a_min, a_max, out=None, **kwargs)`
- `torch.clip(input, min=None, max=None, *, out=None)`

No name is ideal - `min`/`max` are nicer names, but not everyone may be happy that it conflicts with builtin names. `a_min` and `a_max` are bad though, given that we consistently name our input arrays `x` and not `a`. So how about:

```python
def clip(x, min, max, /):  # all positional-only args to avoid incompatibilities
```

**Comment by shoyer** [comment]
> No name is ideal - `min`/`max` are nicer names, but not everyone may be happy that it conflicts with builtin names. `a_min` and `a_max` are bad though, given that we consistently name our input arrays `x` and not `a`. So how about:
> 
> ```python
> def clip(x, min, max, /):  # all positional-only args to avoid incompatibilities
> ```

I would lean towards`clip(x, /, min=None, max=None)`. The naming conflict is only inside the array library, not in user code, which can call these variables whatever it likes.

Side note: this is yet another example (like `unstack` and `moveaxis`) of functionality that could perhaps have a universal default implementation terms of other array API functionality (specifically `where`).

**Comment by rgommers** [comment]
> The naming conflict is only inside the array library, not in user code, which can call these variables whatever it likes.

Only if they're positional, right? 

I actually do like your signature better - `clip(x, max=3)` is nicer than having to write `clip(x, None, 3)`. It's just another thing then that we have to deal with when we aim to converge NumPy's main namespace to the array API standard. But I guess it's not too bad, there's already `**kwargs` in `np.clip`, so using aliases is easy.

**Comment by shoyer** [comment]
> > The naming conflict is only inside the array library, not in user code, which can call these variables whatever it likes.
> 
> Only if they're positional, right?

I only get lint errors for overriding builtins if I define variables with the same name as a builtin. Something like `clip(x, max=3)` is fine -- the lint error is defining a variable named `max`, not for using a keyword argument.

`clip(x, max=max)` would be problematic, but there's nothing in the interface that requires calling the variable `max`. Users can write something like `clip(x, max=a_max)` if desired.

**Comment by jakirkham** [comment]
cc @seberg (in case you have thoughts here)

**Comment by seberg** [comment]
I agree that clip is clear enough that it seems fine to allow passing positional and `min`, `max` seems OK (no strong opinions on it though).
I would lean against `a_min`, etc. even if that is what NumPy has.  The alternative I may seriously consider is `lower` and `upper` (I have not quite made up my mind whether that is the better or worse name for bounds – mathematically speaking).

**Comment by rgommers** [comment]
Questions that were brought up yesterday:
- Should the `min` and `max` inputs participate in determining the output dtype, or should the output dtype equal the input dtype?
  - Tentative answer: `== input_dtype`
- Are `min` and `max` allowed to be arrays, or only scalars? 
  - Tentative answer: yes, because otherwise there's no way to clip along an axis.

@leofang also suggested that `unstack` may be a convenience function, because it's easy to implement as a list comprehension. I tried, and that doesn't actually seem true when it has an `axis` keyword:
```python
>>> x = np.arange(6).reshape((2, 3))
>>> axis = 0
>>> tuple(x[i, ...] for i in range(x.shape[axis]))
(array([0, 1, 2]), array([3, 4, 5]))
>>> axis = 1
>>> tuple(x[:, i, ...] for i in range(x.shape[axis]))  # see different index expression
(array([0, 3]), array([1, 4]), array([2, 5]))
```
In addition, one also needs to deal with `axis` normalization to handle negative axis values. The [JAX `unstack` implementation](https://github.com/google/jax/blob/2b0542dd60a288c81c77382badca12ea169f65f7/jax/_src/numpy/lax_numpy.py#L4837) is instructive:
```python
def _unstack(x):
  return [lax.index_in_dim(x, i, keepdims=False) for i in range(x.shape[0])]

def index_in_dim(operand: Array, index: int, axis: int = 0,
                 keepdims: bool = True) -> Array:
  """Convenience wrapper around slice to perform int indexing."""
  index, axis = core._canonicalize_dimension(index), int(axis)
  axis_size = operand.shape[axis]
  wrapped_index = index + axis_size if index < 0 else index
  if not 0 <= wrapped_index < axis_size:
    msg = 'index {} is out of bounds for axis {} with size {}'
    raise IndexError(msg.format(index, axis, axis_size))
  result = slice_in_dim(operand, wrapped_index, wrapped_index + 1, 1, axis)
  if keepdims:
    return result
  else:
    return lax.squeeze(result, (axis,))
```

**Comment by oleksandr-pavlyk** [comment]
if `min` and `max` do not participate in the type promotion, this makes `clip` not equivalent to `xp.maximum(xp.minimum(x, min), max)` in functional behavior.  

In NumPy both `clip`'s `min` and `max` arguments participate in the type promotion:

```
In [3]: np.clip(np.arange(10, dtype=np.int8), 0, np.inf)
Out[3]: array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
```

**Comment by seberg** [comment]
I don't want to volunteer it, but it shouldn't be hard to change that in NumPy or fix in a compat namespace.  And yes, it will mean that it isn't the same as a chained minimum/maximum call.

**Comment by kgryte** [comment]
At this point, I'd find it a bit inconsistent if `clip` does not follow type promotion rules.

We explicitly changed, e.g., the [`bitwise_left|right_shift`](https://github.com/data-apis/array-api/pull/201) specifications to ensure consistent type promotion rules throughout.

At the time of original API addition, I had advocated for returning an array having a dtype of the same type, but objections were raised (in PyTorch) about having certain APIs exempt from normal type promotion rules.
