### ISSUE TITLE
type hint error from mypy

### ISSUE THREAD

**Issue by mattbarrett98** [data-apis/array-api#489]
mypy doesn't seem to like the type hint `Optional[Union[int, float, Literal[inf, - inf, 'fro', 'nuc']]]` for matrix_norm, giving
```error: Parameter 1 of Literal[...] is invalid```

**Comment by asmeurer** [comment]
Yes, mypy doesn't like floating point literals in `Literal`. So this is a question of whether we should aim for correctness in the type hints or aim to please mypy.

**Comment by mattbarrett98** [comment]
Okay. Also is `float` necessary? The accepted values seem to be `int`s, except for `inf` but this is in the `Literal`.

**Comment by honno** [comment]
> Okay. Also is `float` necessary? The accepted values seem to be `int`s, except for `inf` but this is in the `Literal`.

Assumedly the spec here means to say you can use float-integers (e.g. `1.`, `2.`, `-1.`, ...), which indeed is what implementations seem to support.
