### ISSUE TITLE
Adding `choose`

### ISSUE THREAD

**Issue by jakirkham** [data-apis/array-api#492]
In discussion today around `clip` and `where`, `choose` came up as something we may want to include. A starting point would be [`np.choose`]( https://numpy.org/doc/stable/reference/generated/numpy.choose.html ). Basically this takes an index array and a `list` of arrays (to index into) to build an array that is an amalgamation of the arrays `list`ed.

It is worth noting `where` can be formulated in terms of `choose` where the index array selects between just two arrays. Namely `where(c, a, b) == choose(c, [b, a])`.

**Comment by jakirkham** [comment]
cc @rgommers

**Comment by kgryte** [comment]
As this proposal is without a champion and does not yet have widespread ecosystem support, I'll close. We can revisit/reopen in the future should we see greater consensus and downstream need.
