### ISSUE TITLE
Use similar promotion rules in trace() as sum() and prod()

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#493]
`sum()` and `prod()` use special promotion rules (see https://github.com/data-apis/array-api/issues/202 and https://data-apis.org/array-api/latest/API_specification/generated/signatures.statistical_functions.sum.html#signatures.statistical_functions.sum). `trace()` is effectively a sum over the diagonal, so it should use the same rules. `np.trace()` currently already acts the same as `np.sum()` in this regard. 

Presumably this also means we should add a dtype argument to `trace()`

**Comment by asmeurer** [comment]
Also `np.trace()` does have a `dtype` argument https://numpy.org/doc/stable/reference/generated/numpy.trace.html.

**Comment by rgommers** [comment]
Agreed with `trace` needing the special casting rule and also with it needing a `dtype` keyword, thanks @asmeurer.
