### ISSUE TITLE
fftfreq, rfftfreq are missing device keyword

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [data-apis/array-api#500]
These are constructors, there should be a way to control the device where memory is to be allocated.

Current signatures:

```
fftfreq(n: int, /, *, d: float = 1.0) → array
rfftfreq(n: int, /, *, d: float = 1.0) → array
```

**Comment by rgommers** [comment]
That seems like a valid point to me. All array creation functions have `dtype=None, device=None` keywords.

**Comment by kgryte** [comment]
Based on the 11/3/2022 meeting, consensus was to move forward with adding `dtype` and `device` support.

**Comment by leofang** [comment]
Good catch!
