### ISSUE TITLE
Clarify extensions should live in specified namespaces

### ISSUE THREAD

**Issue by honno** [data-apis/array-api#501]
I noticed our newly introduced FFT stubs live in `fourier_transform_functions.py`, which might implicitly communicate those extensions should live in the `xp.fourier_transform_functions` namespace (`xp` being the top-level Array API namespace), where presumably we want adopters to use `xp.fft` like say NumPy has it.

So that can be renamed, but this brings up that there's no explicit clarification in the spec that the `linalg` and `fft` extensions should indeed live in those respective namespaces. I think a note could live in all extension pages (currently just [Linear Algebra](https://data-apis.org/array-api/draft/extensions/linear_algebra_functions.html) and [Fourier transform Function](https://data-apis.org/array-api/draft/extensions/fourier_transform_functions.html)) explaining that the respective functions should be present in these specific namespaces.

**Comment by honno** [comment]
In todays meeting we were in agreement for both points (`fourier_transform_functions.py -> fft.py` and the notes), so I'll submit a PR.

**Comment by honno** [comment]
I completely missed #470, which aims to do the latter point (note that these extensions must live in specified namespaces).

**Comment by rgommers** [comment]
Fixed by gh-470
