### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#507]
We should add a changelog that lists all the changes between versions. That will make it easier for implementers to see what they need to update in their implementations.

Additionally, we can use the `versionadded` and `versionchanged` Sphinx directives (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded) to add a note to each respective function about things that have changed, which will make it easier to see what changed for a specific functionality.

**Comment by rgommers** [comment]
The changelog has been added in gh-574. The `versionadded` and `versionchanged` directives can be added based on that later - that'll be a task for after the v2022 release

**Comment by kgryte** [comment]
`versionadded` and `versionchanged` directives have been added to the specification. As such, will go ahead and close this one out.
