### ISSUE TITLE
Computing the sign of a complex number

### ISSUE THREAD

**Issue by kgryte** [data-apis/array-api#545]
Originally discussed in <https://github.com/data-apis/array-api/issues/153#issuecomment-869059671>.

In order to add complex support to `sign`, we need to agree on the definition for complex numbers.

NumPy uses `sqrt(z^2)/z` while an arguably more common convention is `x/|x|`.

For paths forward we have 3 options:

1. Use NumPy's definition.
2. Use the more common convention used elsewhere (MATLAB, Julia, etc).
3. Not support complex numbers in `sign`.

## Questions

- If we choose (2), given NumPy's potential v2 release, would NumPy be willing to introduce this breaking change?

## See Also

- <https://github.com/numpy/numpy/issues/3621>
- <https://github.com/numpy/numpy/issues/13179>
- MATLAB: <https://www.mathworks.com/help/matlab/ref/sign.html>
- Julia: <https://docs.julialang.org/en/v1/base/math/#Base.sign>

**Comment by rgommers** [comment]
As discussed in a couple of places, the `z/|z|` definition seems clearly better and preferred, also for numpy. Not sure of a timeline for introducing that (breaking changes are always tricky), but I think in this case it's not like they're two equal alternatives. In the standard I think we should go with `z/|z|`; numpy may not be compliant on that point for a while.
