### ISSUE TITLE
Should there be a integral and floating ABCs?

### ISSUE THREAD

**Issue by NeilGirdhar** [data-apis/array-api#581]
That is, should `np.integral`, `np.floating`, and `np.complexfloating` base classes be available in the Array API?  This would allow other packages to create their own subtypes.  Jax for example has additional floating dtypes.

**Comment by rgommers** [comment]
Hi @NeilGirdhar, thanks for asking. Whether dtypes should have a class hierarchy and how to check whether a dtype is of a certain kind was pretty extensively discussed in:
- gh-425
- gh-152
- also relevant: https://github.com/numpy/numpy/issues/17325

tl;dr not many libraries have a class hierarchy like numpy does, and it doesn't seem either necessary or a good idea to impose one in the standard

> This would allow other packages to create their own subtypes. Jax for example has additional floating dtypes.

There should be no issue with JAX including additional dtypes in what [isdtype](https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html#array_api.isdtype) does. Or have them work with `dtype=` keywords. Do you see a concrete problem with the current design?

**Comment by NeilGirdhar** [comment]
Thanks for the links.  I've read over the discussion now.

> There should be no issue with JAX including additional dtypes in what [isdtype](https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html#array_api.isdtype) does. Or have them work with dtype= keywords. Do you see a concrete problem with the current design?

How are you supposed to do type annotations with the current design?  How are type checkers supposed to verify that an array has a floating dtype for example?   For example, https://github.com/NeilGirdhar/tjax/blob/main/tjax/_src/annotations.py#L24

**Comment by NeilGirdhar** [comment]
I'm going to comment in that thread.
