### ISSUE TITLE
Bug: `indexing` kwarg is no longer keyword-only in `meshgrid`

### ISSUE THREAD

**Issue by kgryte** [data-apis/array-api#599]
In [gh-145](https://github.com/data-apis/array-api/pull/145/files#diff-f8b551edf45aca0f0a5926e0a6f4408c45f7a43ce0773d42179f5a16c1a99df9R293), the `indexing` parameter was keyword-only.

However, during the conversion from Markdown to reST in [gh-348](https://github.com/data-apis/array-api/commit/2f53fdeade62807a04912c0868c594a1d8955cb3#diff-5ae871e8e73c6746050b841eb3232de4b67c66c36e3758c177db4d847f3128c6R227), the `indexing` parameter mistakenly became positional.

The specification should be corrected to address this regression.

**Comment by steff456** [comment]
I have a quick question about this one, right now the signature for `meshgrid` looks like this,

```
def meshgrid(*arrays: array, indexing: str = 'xy') -> List[array]
```

I thought that everything after the first `*` will be keyword only, given that we cannot type `/, *` as there's already a `*`.

Do you prefer to have it written as follows?

```
meshgrid(arrays: array, /, *, indexing: str = "xy") -> List[array]:
```

But then I we will need to change the type of `arrays` for it to have more semantic sense to something like `Union[array, list]`?

**Comment by rgommers** [comment]
The `*` in `*arrays` means "a variable number of positional-only inputs, not keyword-only.

**Comment by steff456** [comment]
The linter is complaining when I do 😅🙃

```
meshgrid(arrays: array, /, *, indexing: str = "xy") -> List[array]:
```

**Comment by rgommers** [comment]
Ah that makes sense. `indexing` is keyword-only already, because all positional args are soaked up by `arrays`. So this is not a bug, the signature is fine as is.
