### ISSUE TITLE
Bug: descriptions for constants included in the standard are incorrect

### ISSUE THREAD

**Issue by kgryte** [data-apis/array-api#601]
See screenshot below:

![image](https://user-images.githubusercontent.com/2643044/219914462-cf99e986-17d4-4700-b403-d2cb7c019119.png)

This affects all currently rendered specification versions.

**Comment by honno** [comment]
I'll have a look next week if no one else does, I think I at one point encountered and fixed this, then regressed that somehow :sweat_smile:

**Comment by rgommers** [comment]
I had a quick look. The descriptions are in strings in `.py` files below the actual constants. `autosummary` doesn't work like that AFAIK, I think these descriptions belong in the `.rst` files instead. Or am I missing anything here?

**Comment by kgryte** [comment]
@honno were you able to address this?

**Comment by honno** [comment]
> were you able to address this?

Nope, did play around a bit a few weeks back but nothing worked, need to find some time to sit down and try again.
