### ISSUE TITLE
reshape, broadcast_to, and permute_dims do not accept a single integer

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#608]
`reshape`, `broadcast_to`, and `permute_dims` (I think these are all but I could have missed one), all accept a `Tuple[int, ...]`. The `shape` parameter for `reshape` and `broadcast_to` for `shape`, and `axis` for `permute_dims` 

Every other function that accepts this kind of parameter accepts `Union[int, Tuple[int, ...]]`.

It was pointed out in https://github.com/data-apis/array-api-compat/issues/28 that NumPy currently accepts ints for all of these (and indeed, numpy.array_api accidentally does), but PyTorch does not.

**Comment by kgryte** [comment]
IIRC, the use of an integer is not the dominant use case and is more of shorthand in NumPy. In <https://github.com/data-apis/array-api/pull/42>, we explicitly favored Torch (and somewhat TF) in restricting to a tuple for `reshape`.

For `permute_dims`, providing an integer does not make sense as a shorthand, except for the trivial case of a 1d array.

In general, I'd argue that a `shape` kwarg should be a tuple. If NumPy wants to support an integer shorthand, that's its prerogative, but I don't think this should be codified in the spec.

**Comment by rgommers** [comment]
> Every other function that accepts this kind of parameter accepts `Union[int, Tuple[int, ...]]`.

The only instances of `shape` parameters are for creation functions (`ones` & co) and manipulation functions (the ones you mentioned. The former accept ints, because `ones(3)` is a super common shorthand. The latter all require a tuple. So I'm inclined to agree with @kgryte here and say that the current state is fine, and preferred over allowing `reshape(3)`.

**Comment by rgommers** [comment]
Since this was reviewed in gh-42, there are good reasons for this, and https://github.com/data-apis/array-api-compat/issues/28 is already closed, let's close this one too.

Thanks @asmeurer and @kgryte
