### ISSUE TITLE
Versions menu doesn't keep you on the same page

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api#620]
When you choose a different version in the versions menu, it doesn't keep you on the same page. It moves you back to the main page for that version.

I have some Javascript (feel free to reuse) in SymPy that makes it so the version selector in the SymPy docs keeps on the same page if possible https://github.com/sympy/sympy/blob/master/doc/src/_templates/sidebar/versions.html (see the "documentation version" at the right side of the page at https://docs.sympy.org/latest/index.html). Hopefully this can be adapted to the version selector for our docs theme. 

It also doesn't actually list what the current version is anywhere on the page. The only place this information is available is in the page URL. It should state the version somewhere in the clearly in the header, especially if the version isn't "latest".

**Comment by asmeurer** [comment]
Also I should note if you use this Javascript with Sphinx 5.0 you need to add sphinxcontrib-jquery as a Sphinx extension dependency (or alternatively, you could try to rewrite it without jquery a la https://github.com/sympy/sympy/pull/24989#issuecomment-1490798238).

**Comment by kgryte** [comment]
This issue was resolved in follow-up PR: https://github.com/data-apis/array-api/pull/650.

**Comment by kgryte** [comment]
One aspect mentioned in the OP which has not been addressed is displaying the current documentation version clearly on the page. Currently, you still have to examine the URL to determine the version. I suggest opening a new issue for addressing this.
