### ISSUE TITLE
sum docstring's description of dtype=None behavior is muddled

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [data-apis/array-api#623]
The first bullet-point of https://data-apis.org/array-api/latest/API_specification/generated/array_api.sum.html describing behavior for `dtype=None` value stipulates an override condition (if data type of `x` has wide range than default data-type, use the data type of `x`), but the subsequence bullet-points unconditionally require output of the default data type for respecting input data type kinds, without acknowledging the exception stated in the first bullet-point. 

I wish this description was made clearer. My read is points 2, 3, and 4 hold except in cases stipulated in point 1.

**Comment by kgryte** [comment]
@oleksandr-pavlyk Your reading is correct. Agreed that we should be clearer in that regard. Will work on a PR to which clarifies.
