### ISSUE TITLE
Plans for support of a random number generation API?

### ISSUE THREAD

**Issue by adonath** [data-apis/array-api#671]
Many of the the libraries such as `numpy`, `torch`, `jax` etc. have support for random number generation. Typically in their own namespace, or exposed via a `Generator` API. Are there any plans to extend the API standard for random number generation using arrays? I am aware this poses a lot of challenges in terms of reproducibility across multiple implementations, but maybe this has been discussed in the past already and has been discarded for not being in scope?

**Comment by honno** [comment]
See https://github.com/data-apis/array-api/issues/431 for some interesting convo on the subject. We concluded with

> Given lack of ecosystem agreement, we are not likely to forge a path forward for standardizing a PRNG API in the array API specification at this time. [...] We can reopen/revisit if and when we have greater community consensus.

I'll close this issue, but please do feel free to continue the conversation on #431.

**Comment by rgommers** [comment]
I'd add that we will probably try to build an implementation soon for SciPy's usage (since we need it in quite a few places) that exposes a uniform API and works with NumPy, PyTorch, CuPy and JAX at least.

**Comment by adonath** [comment]
Great thanks, @rgommers and @honno!

**Comment by NeilGirdhar** [comment]
Is there any update on random number generation available somewhere?
