### ISSUE TITLE
Clarification needed for spec of xp.roll

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [data-apis/array-api#679]
Per [spec](https://data-apis.org/array-api/latest/API_specification/generated/array_api.roll.html) for `xp.roll`: 

>  If `shift` is a tuple, then `axis` *must* be a tuple of the same size, and each of the given `axes` must be shifted by the corresponding element in `shift`.

The verbiage appears to be identical to that from [documentation](https://numpy.org/doc/stable/reference/generated/numpy.roll.html) of `np.roll` . 

NumPy does allow the combination of `shift` a tuple and `axis=None`. So I'd like to clarify that Array API spec does actually require and exception for such an input:

```python
import numpy as np
x = np.arange(24).reshape((2,3,4))
y = np.roll(x, shift=(1,1))   # this works, but should it raise?
yy = np.roll(x, 2)
np.array_equal(y, yy)
# returns True
```

**Comment by rgommers** [comment]
I believe the wording is correct, because:
```python
>>> import torch
>>> t = torch.arange(24).reshape((2,3,4))
>>> ty = torch.roll(t, (1,1), dims=(0,1))
>>> ty = torch.roll(t, (1,1))
Traceback (most recent call last):
  Cell In[29], line 1
    ty = torch.roll(t, (1,1))
RuntimeError: shifts and dimensions must align. shifts: 2, dims:0
```

**Comment by kgryte** [comment]
@oleksandr-pavlyk Are you okay closing this issue, given that the wording for `roll` is an intended?
