### ISSUE TITLE
Type hints of the form `Union[int, float]` are redundant

### ISSUE THREAD

**Issue by aaronmondal** [data-apis/array-api#680]
The typehint `Union[int, float]`, or `int | float` could just be `float`.

`int` is a subclass of `float`: https://docs.python.org/3/library/numbers.html#the-numeric-tower

**Comment by honno** [comment]
Yeah IIRC we did this to be explicit that functions inputting/outputting the builtin `float` also cover `int`, as the numeric tower isn't obvious.

**Comment by asmeurer** [comment]
This has come up before. The PEPs do say this, but we should consider that the array API doesn't follow the numeric tower. Considering int to be a subtype of float is problematic, and we want to instead treat integer types as distinct from floating-point types. 

I thought I remembered a function that accepted float but not int (thought it was `__floordiv__` or `__truediv__` but maybe I'm misremembering, or maybe it was changed?).

**Comment by rgommers** [comment]
Agreed. While the static typing comment is correct, we don't want to change this. The type hints are not only for static typing tools, but they are documentation - and treating ints and floats separately here is useful.

Therefore I'll close this issue. Thank you for the suggestion though @aaronmondal!
