### ISSUE TITLE
RFC: add support for JAX's `at[].set()` syntax

### ISSUE THREAD

**Issue by albert-mathews** [data-apis/array-api#734]
Hello, sorry if I'm raising a question that has been raised/addressed, but I [asked the question](https://github.com/numpy/numpy/issues/25576) in Numpy repo, and was directed here. 

I think these issues in this repo are relevant:
https://github.com/data-apis/array-api/issues/669
https://github.com/data-apis/array-api/issues/177

In may case i dont care whether the take/put op is in-place or on immutable arrays, all i care about is that Numpy and JAX support identical syntax such that i can either `import numpy as array_lib` or `import jax.numpy as array_lib`, and then use all the same code thereafter. 

thanks for all the hard work developing an array standard.

**Comment by kgryte** [comment]
Closing this issue in favor of the existing discussion on https://github.com/data-apis/array-api/issues/609.
