### ISSUE TITLE
version switcher on deployed website disappeared

### ISSUE THREAD

**Issue by rgommers** [data-apis/array-api#753]
Almost certainly caused by gh-735. 

Also xref a related issue with a JS warning about the search results, which was also due to a Sphinx version upgrade: https://github.com/data-apis/data-apis.github.io/issues/24.

**Comment by rgommers** [comment]
This works in the demo site of the theme (see [here](https://bashtage.github.io/sphinx-material/customization.html, also for docs on version dropdown usage).

We have a slightly unusual setup here, but it's not clear what changed beyond an upgrade of Sphinx. Things do seem to land in the right places in the `gh-pages` branch.

A bit of info:
- the dropdown was added in gh-394,
- Sphinx config is at https://github.com/data-apis/array-api/blob/fa04c35c87708fa565a4a8f6bb8360ae836ac5d7/src/_array_api_conf.py#L174-L175
- versions are specified in https://github.com/data-apis/array-api/blob/main/spec/_ghpages/versions.json
- running `make` in the root of the repo reproduces the problem locally
- debugging the deployed site in the browser shows `Uncaught ReferenceError: $ is not defined`, which points at the `add_version_dropdown` line of:
```
  <script src="_static/javascripts/version_dropdown.js"></script>
  <script>
    var json_loc = "../versions.json",
        target_loc = "../",
        text = "Versions";
    $( document ).ready( add_version_dropdown(json_loc, target_loc, text));
  </script>
```

Someone with more JavaScript skills can take it from here I hope:)

**Comment by asmeurer** [comment]
I think it has to do with jquery. There was some change in sphinx at some point where they stopped shipping it or something like that.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/pull/24989. The fix here is probably the same.
