### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by honno** [data-apis/array-api#756]
The `gh-pages` branch was accidentally deleted this morning (by someone who's username rhymes with Bono :thinking:), which left https://data-apis.org/array-api/ giving a 404 error.

I made and pushed a [`gh-pages` branch](https://github.com/data-apis/array-api/tree/gh-pages) with a local build of the spec, as well as re-running the [latest `publish` CI job
](https://github.com/data-apis/array-api/actions/runs/8045716787/job/22084519697) to no avail—in both instances I got "No [CircleCI] configuration was found in your project." ([details](https://app.circleci.com/pipelines/gh/data-apis/array-api/1409)). I don't recall having a CircleCI config in `gh-pages` repo too, but maybe we did? Checking the relevant PRs and discussions I don't believe so, but can't verify this. I also don't have access to the CircleCI account.

I think next steps is to:
- [ ] Check this repo's settings (I don't have access) to see if any GitHub pages related setting needs to be re-checked/etc.
- [ ] See if anyone has `gh-pages` locally and give a file diff of the remote branch.

**Comment by rgommers** [comment]
- Site is back up
- I've restored the `gh-pages` branch, which I had locally with history up to a week ago. It may miss the raw html for a couple of deploys, but that doesn't really matter
- I have also enabled branch protection for the `gh-pages` branch (in addition to `main`)

There was nothing else to no to fix CircleCI, the site came back up after the gh-pages branch was restored.
