### ISSUE TITLE
Let's change master to main 

### ISSUE THREAD

**Issue by willingc** [data-apis/array-api#78]
Updating the branch now before stuff grows will make things easier.

**Comment by rgommers** [comment]
Thanks @willingc! I agree, that's a good thing to do, and is easy to now given that there are no forks yet or open PRs.

**Comment by rgommers** [comment]
I'll do this tomorrow if there are no objections by then. And while we're add it, let's do it for the other repos in this org as well.

**Comment by asmeurer** [comment]
I've held off on migrating in my own repos because GitHub has stated that they are still developing tools to make migrating easier.

**Comment by willingc** [comment]
@asmeurer Yeah, I've held off migrating larger projects too for the same reason. For the smaller/newer projects, I've moved to main sooner.

**Comment by asmeurer** [comment]
One question that I've had is if there's some way to make git globally alias `main` for `master` or vice versa. You can do it on a per repo basis with https://stackoverflow.com/a/23532744/161801, but I don't know if that can be done globally. Otherwise I can easily see a nightmare of trying to remember "these repos use 'main' and these repos use 'master'".

**Comment by willingc** [comment]
@asmeurer Not that I'm aware of. My command line displays the branch and I almost always leave the directory in main or master when exiting it. I use `alias gitup="git fetch upstream && git rebase upstream/main 2> /dev/null || git rebase upstream/master"` Works well enough for my workflow. YMMV. If you do find something globally, please do pass along.

**Comment by rgommers** [comment]
Okay done, on all repos except `array-api-tests` (@asmeurer can you do that one?) and `python-record-api` (that one has several open PRs and a complex CI setup, so not touching it right now).
