### ISSUE TITLE
Confusing example in "Copy-view behaviour and mutability"

### ISSUE THREAD

**Issue by eric-wieser** [data-apis/array-api#82]
I find this example very confusing:

> This happens when views are combined with mutating operations. This simple example illustrates that:
> ```python
> x = ones(1)
> x += 2
> y = x   # `y` *may* be a view
> y -= 1  # if `y` is a view, this modifies `x`
> ```

The semantics of Python mean that `y = x` _always_ makes `y` a "view" of x - `x is y` by definition.

I think the point this example is trying to make is that _"if `-=` operates in place, this modifies `x`"_ - but the comments tell a different and incorrect story.

Either that, or the example should include a slice operation of some kind, where the library actually does have an chance to decide whether to make a copy or view.

**Comment by rgommers** [comment]
Thanks for bringing that up @eric-wieser. "view" here means the numpy/pytorch concept of view, which I think has little to do with Python language semantics. 

> Either that, or the example should include a slice operation of some kind, where the library actually does have an chance to decide whether to make a copy or view.

That was my first though. Would changing to:
```
y = x[:]  # `y` *may* be a view on the data of `x`
```
resolve this confusion?

**Comment by eric-wieser** [comment]
Yes, that would definitely resolve it

**Comment by rgommers** [comment]
Done now, thanks @eric-wieser
