### ISSUE TITLE
Wording in default_dtypes does not leave room for unsupported data types

### ISSUE THREAD

**Issue by cbourjau** [data-apis/array-api#827]
The documentation of [`default_dtypes`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.info.default_dtypes.html#array_api.info.default_dtypes) reads as of today:

  
    Returns a dictionary containing default data types.
    
    The dictionary must have the following keys:
  
      - "real floating": default real floating-point data type.
  
      - "complex floating": default complex floating-point data type.
  
      - "integral": default integral data type.
  
      - "indexing": default array index data type.
      
The "must" poses an issue for implementations that don't implement all data types, yet, such as `ndonnx` (related [discussion](https://github.com/Quantco/ndonnx/pull/32)). Maybe wording this as "...may at most contain the following keys..." is more appropriate?

**Comment by asmeurer** [comment]
So far the standard has required all data types. There was some discussion about loosening this, but I don't remember if there was a resolution on it, or if we actually have an issue for it already.

**Comment by cbourjau** [comment]
Oh, I see! Thanks for the clarification! I was under the impression that a subset may be allowed, but it clearly isn't: https://data-apis.org/array-api/2023.12/API_specification/data_types.html. I believe it does indeed make sense to require all data types so I'm closing this issue.
