### ISSUE TITLE
API specification seems to assume all arrays are floats

### ISSUE THREAD

**Issue by eric-wieser** [data-apis/array-api#83]
The description of [`__abs__`](https://data-apis.github.io/array-api/latest/API_specification/array_object.html#abs-x) and especially [`__add__`](https://data-apis.github.io/array-api/latest/API_specification/array_object.html#add-x1-x2)  seems to try to go into great detail about how floating point addition / `abs` works.

I'd argue this obscures the intent behind what is ultimately a container API, and it would be better to refer to the IEEE 754 spec (or perhaps add a separate page summarizing IEEE 754)

**Comment by rgommers** [comment]
That does sound like a good idea to make things easier on the reader. A separate page summarizing IEEE 754 sounds good to me, because that standard is non-free as well as painful to read.

**Comment by kgryte** [comment]
Rather than add a separate page, an alternative could be to place IEEE 754 details, or special cases in general, within a [collapsible HTML section](https://sphinx-toolbox.readthedocs.io/en/latest/extensions/collapse.html) (aka, a `details` element).
