### ISSUE TITLE
Data type objects for libraries with multiple backends

### ISSUE THREAD

**Issue by lucascolley** [data-apis/array-api#832]
In the most recent Dask community meeting I raised https://github.com/dask/dask/issues/10387 regarding exposing dtype objects in the `dask.array` namespace. The discussion raised the question of what Dask should return here given that their array objects can have several different objects for each data type, depending on the array backend (e.g. `np.float64` or `cp.float64`...). EDIT: CuPy is a bad example here as the dtypes are aliases for the NumPy dtypes.

Perhaps it is possible to dynamically look up which array backend is being used, however there were concerns raised about import-time lockins and what to do when multiple array backends are used in the same workflow.

Perhaps it is good enough for now for `dask.array` to just expose the `np` dtypes (this would unblock CPU testing in SciPy at least over at https://github.com/scipy/scipy/pull/20956). Indeed, this is what [the array-api-compat dask wrapper](https://github.com/data-apis/array-api-compat/blob/d57c6710b42d597a75be9c7bcd2d7a6372e13b03/array_api_compat/dask/array/_aliases.py#L9-L34) does right now. However, there were concerns raised about a potential deprecation cycle being needed in the future. 

Is there any guidance that the standard can give here?

Pinging from the discussion @jacobtomlinson @fjetter @jrbourbeau @rjzamora

cc @ogrisel @jakirkham @tomwhite

**Comment by leofang** [comment]
I do not understand what's the ask here, could you clarify for me? 

For the specific case of Dask, note that CuPy does not have its own dtype system and by design all CuPy dtypes are just alias of NumPy dtypes. So for Dask users it's sufficient to just check against NumPy dtypes.

**Comment by lucascolley** [comment]
Ah, so CuPy is a poor example then. But it sounded from the discussion like there are other backends for which the dtypes would not be aliases. I'm sure one of the Dask folks can clarify.

**Comment by leofang** [comment]
The expectation is for an array library to expose its dtype objects, under the array namespace:
> A conforming implementation of the array API standard must provide and support the following data types (“dtypes”) in its array object, and as data type objects in its main namespace under the specified names:

and the dtype objects need to at least have a `__eq__` method. 
https://data-apis.org/array-api/latest/API_specification/data_types.html

Is this issue about the dtype objects have ambiguity when an array library is backed by multiple other array libraries under the hood?

**Comment by lucascolley** [comment]
> Is this issue about the dtype objects have ambiguity when an array library is backed by multiple other array libraries under the hood?

Yeah

**Comment by asmeurer** [comment]
The standard says that data type objects can be anything. The only requirement is that they implement `__eq__` https://data-apis.org/array-api/latest/API_specification/data_types.html. A library could even set `float64 = "float64"` if it wanted to. So there's no reason a library can't reuse NumPy dtype objects.

For Dask, if there are multiple backends, the only concern I can think of is whether switching backends would break existing dtype objects. Conversely, there might be use-cases for dask (outside of the scope of the standard) where you want to make sure that dask dtypes work with NumPy, so reusing NumPy dtypes would be useful. In that case, it just needs to make sure it forwards the dtype objects to the backends correctly.

**Comment by lucascolley** [comment]
Okay, I did my homework, and as far as I can see from the Dask docs, the supported backends for `dask.array` are `numpy`, `cupy` and `sparse`. Indeed:

```python
>>> import numpy as np, cupy, sparse
>>> cupy.float64 is np.float64
True
>>> sparse.float64 is np.float64
True
```

So, at least with the current backends, exposing the NumPy dtypes in https://github.com/dask/dask/pull/11178 does not seem incorrect. There shouldn't be any concerns about multiple backends being used in the same workflow.

Perhaps one of the Dask folks pinged above would be willing to review https://github.com/dask/dask/pull/11178, or point me to someone who would be?

**Comment by jacobtomlinson** [comment]
I feel pretty convinced by that. Other Dask maintainers didn't seem to have strong feelings so I've gone ahead and merged your PR @lucascolley.

**Comment by lucascolley** [comment]
thanks a lot @jacobtomlinson ! Will give the next Dask nightly a spin through SciPy.

I feel like this issue could stay open as the standard doesn't really say what to return in the hypothetical future Dask case:

```python
import dask.config
dask.config.set({"array.backend": "something_new"})

import dask.array as da
# da.int64 should be the something_new dtype instead of numpy
```

although indeed the something_new dtype seems like the sensible result. Since this doesn't exist yet, it seems fine to leave this unspecified at least for now, although I think it would be a bit concerning if:

```
xp.asarray(x, dtype=xp.float64)
```

ever produced an error like "`xp.float64` is not compatible with {insert backend for `xp`} arrays".

**Comment by rgommers** [comment]
Nice work!

Regarding the potential future backend concern, I don't think there's an issue (?) since this can always be made to work:
```python
import dask.array as da

da.asarray(x, dtype=da.float64)
```
Aliasing `da.float64` to `np.float64` is a handy shortcut which allows Dask to internally pass on `dtype=dtype` unconditionally, but if there will be a backend in the future that doesn't accept numpy dtypes, then replacing the dtypes with something that supports:
```python
def get_backend_dtype(x, dtype):
    if dtype is not None:
        dtype = dtypes_dict[get_backend(x)][dtype]
    return dtype

def da_func(x, dtype=None):
    backend_dtype = get_backend_dtype(x, dtype)

    da.a_func(..., dtype=dtype)
    x_backend.another_func(..., dtype=backend_dtype)
```
That will work as long as users don't arbitrary mix dtypes from the `dask.array` namespace with functions from a backend array library.

> I feel like this issue could stay open as the standard doesn't really say what to return in the hypothetical future Dask case:

There is no concept of wrapping/backends, so there is nothing that can be said I think. It shouldn't matter as long as user code is written without explicitly mixing objects from different array libraries. And that's a "don't do that" which is one of the first things addressed at https://data-apis.org/array-api/latest/assumptions.html: _"Importantly, array libraries are not assumed to be aware of each other, ...."_

**Comment by lucascolley** [comment]
Right, that makes sense to me. Thanks all!
