### ISSUE TITLE
Will the Array API promise a uniform way to extend arrays?

### ISSUE THREAD

**Issue by NeilGirdhar** [data-apis/array-api#847]
Problem
---
I would like to extend an array type to have some user-defined flags.

Background
---
Various array libraries provide some mechanisms for extending their arrays.  For example, NumPy provides `__array_function__` described in [NEP 18](https://numpy.org/neps/nep-0018-array-function-protocol.html), and Jax provides an undocumented/unrecommended `__jax_array__`.

Example
---
Suppose I would like to add flags to an array type.  Would something like this work?
```python
class HasFlags:
    def __init__(self, flags: dict[str, Any], **kwargs) -> None:
        super().__init__(**kwargs)
        self.flags = flags


class ArrayAPIBase:   # Perhaps have this in array-api-compat?
    """A base class to implement an Array API array by composition."""
    def __init__(self, array: Array, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.array = array

    def __array_namespace__(self):  # noqa: ANN204, PLW3201
        return self.array.__array_namespace__

    dtype = property(lambda self: self.array.dtype)
    shape = property(lambda self: self.array.shape)
    # ...


class FlagArray(ArrayAPIBase, HasFlags):
    pass
```

**Comment by rgommers** [comment]
I think extending by either subclassing or a protocol a la `__array_function__` is impossible to standardize - too hard, no commonality between libraries, and has runtime overhead.

What can be done is wrapping with a new array class, stashing the array API standard-compliant array as a property on a wrapper array instance. @mdhaber has an implementation of masked arrays that do such a thing at https://github.com/mdhaber/marray. I believe it's (almost) fully functional.

**Comment by asmeurer** [comment]
I don't know if @mdhaber's marray is a great example, as it does use subclassing (and notes it will only work in NumPy and CuPy):

https://github.com/mdhaber/marray/blob/e153d6922e4d98df0943c70976e3fcc1d9209f32/marray/__init__.py#L26-L31

The method @NeilGirdhar proposed above that wraps the array object would be much more robust, I would expect. The main thing that's missing from your example is that `__array_namespace__` would need to return some sort of fake namespace object that passes through the wrapped array to the array API namespace functions. I think it should be possible to do this more or less generically with a little bit of metaprogramming. I don't think there should be a need to add any sort of `__array_function__` or something like that to the standard. See also my comments at https://github.com/data-apis/array-api/discussions/843#discussioncomment-10731563.

**Comment by mdhaber** [comment]
> I don't know if @mdhaber's marray is a great example, as it does use subclassing (and notes it will only work in NumPy and CuPy):

This wasn't inherent to the design. I did change that at some point (mdhaber/marray#1), although apparently I didn't push to main. I wrote it that way under the assumption that we'd want it to subclass; if not, there's just a little more work to reproduce the things you want but don't inherit.
