### ISSUE TITLE
Boolean dtypes need not specify storage in bytes

### ISSUE THREAD

**Issue by shoyer** [data-apis/array-api#86]
The current specification is "Boolean ( True or False ) stored as a byte."
https://data-apis.github.io/array-api/latest/API_specification/data_types.html#bool

In my view, storing the data as a byte is an implementation detail not appropriate to include in the specification, particularly given our goal to be hardware agnostic. For example, its should be possible to make a compliant array library that stores booleans in a single bit each.

**Comment by rgommers** [comment]
Thanks @shoyer, good point - fixed now.
